### ISSUE TITLE
Delayed Job

### ISSUE THREAD

**Issue by mihaic195** [veeqo/advanced-sneakers-activejob#17]
Hi there,

new user of sneakers/rabbitmq so might be a noob question.
One issue that I caught was that the original sneakers gem does not provide any way for delayed jobs. It can be handled by installing some rabbitmq addons such as a delayed message exchange or by using a combination of message-TTL and dead-lettering.

From inspecting the code, I've noticed that this approach uses message-TTL and dead-lettering.
Naturally, my first thought is that I don't need any extra plugins for it, or do I?

On a side note, great work on this gem. Seems as it's exactly what I need. Shame it's not so popular yet.

Thanks.

**Comment by sharshenov** [comment]
Hey @mihaic195,

Yes, `advanced-sneakers-activejob` provides delayed jobs support with [a default RabbitMQ installation](https://github.com/veeqo/advanced-sneakers-activejob/blob/ce03ba3445dad92d8a470ea8d19ab336c7168947/.ci/install_rabbitmq#L13-L18). The management plugin is required for tests only as it provides HTTP API required for spec helpers.

But there is a limitation:
delayed jobs will be lost if there is no binding defined at the moment of message death in the delayed queue.

```ruby
GuestsCleanupJob.set(wait: 1.week).perform_later(guest)
# If there are no binding created within 1 week, this job is lost
```

This effect can be avoided by 2 ways:
1. Just start the consumer `rake sneakers:active_job` - it will define corresponding queues and bindings
2. Enqueue the first job without a delay `GuestsCleanupJob.perform_later(guest)`

Another trait to keep in mind is that any unique delay will result a new delayed queue to be created. So having something like `GuestsCleanupJob.set(wait: rand(1.week)).perform_later(guest)` is not a good idea.


<hr>

Thanks for the feedback :heart: 
Actually, there are more projects actively developed for ActiveJob and RabbitMQ setup by Veeqo:
1. [activejob-uniqueness](https://github.com/veeqo/activejob-uniqueness) - job uniqueness for ActiveJob inspired by [sidekiq-unique-jobs](https://github.com/mhenrixon/sidekiq-unique-jobs).
2. Not-yet-public solution for dynamic queue tenancy sharding compatible with `advanced-sneakers-activejob` we keen to make public eventually. It provides fair resources distribution for jobs of different users. Basically, if one user generates 5 jobs (`a`) and another one generates 3 jobs (`b`), then the consumer will get these jobs reordered `a,b,a,b,a,b,a,a`. Similar requirements are described [here](https://github.com/mperham/sidekiq/issues/4208)

Follow [@veeqo_devs twitter](https://twitter.com/veeqo_devs) to stay tuned
