### ISSUE TITLE
Rails 7.0 issue: cannot load such file -- action_mailer/delivery_job

### ISSUE THREAD

**Issue by thanosbellos** [veeqo/advanced-sneakers-activejob#29]
Hi i am using advanced-sneakers-activejob as my queue adapter. I tried to upgrade one project to Rails 7.0.1 and i got the following issue:

```.gem/ruby/3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- action_mailer/delivery_job (LoadError)```

I have managed to make it work by changing this line [here](https://github.com/veeqo/advanced-sneakers-activejob/blob/3abef2d78342cc9dbcc0b24b9d14fff1d81eed5f/lib/advanced_sneakers_activejob.rb#L29)
from:
```  require 'action_mailer/delivery_job' # Enforce definition of ActionMailer::DeliveryJob::Consumer```
to
``` require 'action_mailer/mail_delivery_job' # Enforce definition of ActionMailer::DeliveryJob::Consumer```

ActionMailer::MailDeliveryJob was introduced with Rails 6.0 and it has been the framework default since that version.
ActionMailer::DeliveryJob was present up to Rails 6.1 but it has been removed in Rails 7.0

**Comment by sharshenov** [comment]
@thanosbellos Thanks for the report 

The `main` branch now does support Rails 7.0

```ruby
# Gemfile
gem 'advanced-sneakers-activejob', github: 'veeqo/advanced-sneakers-activejob', branch: 'main'
```

**Comment by thanosbellos** [comment]
Just tested it on a Rails 7.0 project. Everything looks good. Thanks a lot!!
