### ISSUE TITLE
Having issues with calling/finding consumer

### ISSUE THREAD

**Issue by chernesk** [veeqo/advanced-sneakers-activejob#32]
I'm probably going about this all wrong, but would really appreciate some help.

I have a job in `app/jobs/award_print_job.rb` that looks like:
```
class AwardPrintJob < ActiveJob::Base
  queue_as :award_print
  def perform(metadata)
    ....
  end
end
```

and things get queued into Rabbit just fine.

I'm having a problem with having a consumer found. I have in `app/consumers/award_print_consumer.rb`
```
class AwardPrintConsumer
  include Sneakers::Worker
  from_queue :award_print (and I've tried 'award_print'

   def work(msg)
     ...
     ack! 
  end
end
```

And nothing gets pulled off the queue and work is not called.

I'm sure that there's something silly that I'm doing wrong. Could you help point me in the right direction?

Thanks!

**Comment by sharshenov** [comment]
Hey @chernesk 
The purpose of this library is to use the Sneakers as an _adapter_. If you have an ActiveJob class defined, you don't need to have a dedicated Sneakers consumer. The gem does it for you.
Just make sure you have the correct ActiveJob adapter activated for the environment and start the worker.

```ruby
# config/initializers/development.rb and production.rb
config.active_job.queue_adapter = :advanced_sneakers
```

```sh
rake sneakers:active_job
```
https://github.com/veeqo/advanced-sneakers-activejob#usage

**Comment by sharshenov** [comment]
@chernesk I suggest to start the worker process exclusively for the queue

```sh
QUEUES=award_print rake sneakers:active_job
```

If the worker boots correctly you will be able to see its AMQP connection entry on the consumers tab of the queue in RabbitMQ management UI.
