### ISSUE TITLE
ways of acknowledging a job

### ISSUE THREAD

**Issue by abhijeet-branch** [veeqo/advanced-sneakers-activejob#35]
I need to understand the behaviour of setting `:ack => false` in configuration. My expectation was that it will take the job and will acknowledge it and move forward, but instead this is the behaviour I observed mentioned in below steps.

- Put 10k jobs to the queue.
- Start a worker for the job.
- The queue size immediately dropped to zero.
- worker kept on consuming message one by one.

So, this was a bit of unexpected behaviour. Is there a way to make sure that auto acknowledge does not happen for all the jobs in one go otherwise it's hard to productionize it.

Second thing is there a way to configure it on job level, the way Sneakers provide it. https://github.com/jondot/sneakers/wiki/Configuration#local-per-worker

My use case is for a few jobs I want to make them idempotent, so that for those long running job if somehow it doesn't complete in mentioned time, it will not make the job available again in the queue and picked up again by a worker.

**Comment by sharshenov** [comment]
Hey @abhijeet-branch

I believe your configuration disables the manual acknowledgment and the prefetch value is not limited. It allows the consumer to pull all available messages from RabbitMQ and at the same time each message is considered as processed regardless its actual processing state.

> In automatic acknowledgement mode, a message is considered to be successfully delivered immediately after it is sent. This mode trades off higher throughput (as long as the consumers can keep up) for reduced safety of delivery and consumer processing. This mode is often referred to as "fire-and-forget". Unlike with manual acknowledgement model, if consumers's TCP connection or channel is closed before successful delivery, the message sent by the server will be lost. Therefore, automatic message acknowledgement should be considered unsafe and not suitable for all workloads.

https://www.rabbitmq.com/confirms.html#acknowledgement-modes

I suggest to:
1. Set the `prefetch` setting to something meaningful like the number of threads
2. Do not disable the default acknowledgment strategy

Anyway, this issue has nothing related to advanced-sneakers-activejob.

**Comment by abhijeet-branch** [comment]
I was just testing out locally and had set prefetch value as 1 and still that happened, I wouldn't say it's an issue but just some weird behaviour, here is the config used.
`AdvancedSneakersActiveJob.configure do |config|
    config.sneakers = {
      connection: Bunny.new(BUNNY_CONFIG),
      prefetch: 1, # sneakers default: 10
      # Threadpool size (good to match prefetch)
      threads: 1, # sneakers default: 10
      # Number of workers
      workers: 1, # sneakers default: 4
      ack: false,
    }
  end`
